### ISSUE TITLE
Use `with` instead

### ISSUE THREAD

**Issue by j-f1** [rbuckton/proposal-using-statement#8]
This would reduce syntax conflicts by using a reserved word, and would be backwards -compatible because a `VariableDeclaration` is not a valid value for the `WithStatement`.

**Comment by ljharb** [comment]
Repurposing `with` would both mean this feature would require strict mode, and also would make all the documentation for old `with` very confusing. This imo is a nonstarter.

**Comment by Ginden** [comment]
I'm also in favor of `with`or `try with () {} `.

**Comment by rbuckton** [comment]
@j-f1: As @ljharb said, `with` is a non-starter:
- It would make searching for help on the feature much harder due to the legacy usage of `with` in JavaScript.
- It would prevent the use of the declarationless expression form: `using(x) {}`, since `with(x){}` is already legal in non-strict code.

Its my opinion we should avoid using `with` for new syntax in _any_ position where it would share similarity with legacy usage.

@Ginden: As far as `try with () {}`, there would be no need to introduce `with` here, since `try () {}` is usable syntax and already discussed as an alternative to `using` in [the explainer](https://github.com/rbuckton/proposal-using-statement#grammar):
> - We may opt to instead augment _TryStatement_ syntax in a fashion similar to Java's `try`-with-resources, e.g. `try (expr) {}` or `try (let x = expr) {}`, however the oddity of the implied finally might be a source of confusion for users.
